const championshipRoundsIds = [
  { id: "1", synonymous: ["1"] },
  { id: "2", synonymous: ["2"] },
  { id: "3", synonymous: ["3"] },
  { id: "4", synonymous: ["4"] },
  { id: "5", synonymous: ["5"] },
  { id: "6", synonymous: ["6"] },
  { id: "7", synonymous: ["7"] },
  { id: "8", synonymous: ["8"] },
  { id: "9", synonymous: ["9"] },
  { id: "10", synonymous: ["10"] },
  { id: "11", synonymous: ["11"] },
  { id: "12", synonymous: ["12"] },
  { id: "13", synonymous: ["13"] },
  { id: "14", synonymous: ["14"] },
  { id: "15", synonymous: ["15"] },
  { id: "16", synonymous: ["16"] },
  { id: "17", synonymous: ["17"] },
  { id: "18", synonymous: ["18"] },
  { id: "19", synonymous: ["19"] },
  { id: "20", synonymous: ["20"] },
  { id: "21", synonymous: ["21"] },
  { id: "22", synonymous: ["22"] },
  { id: "23", synonymous: ["23"] },
  { id: "24", synonymous: ["24"] },
  { id: "25", synonymous: ["25"] },
  { id: "26", synonymous: ["26"] },
  { id: "27", synonymous: ["27"] },
  { id: "28", synonymous: ["28"] },
  { id: "29", synonymous: ["29"] },
  { id: "30", synonymous: ["30"] },
  { id: "31", synonymous: ["31"] },
  { id: "32", synonymous: ["32"] },
  { id: "33", synonymous: ["33"] },
  { id: "34", synonymous: ["34"] },
  { id: "35", synonymous: ["35"] },
  { id: "36", synonymous: ["36"] },
  { id: "37", synonymous: ["37"] },
  { id: "38", synonymous: ["38"] },
  { id: "39", synonymous: ["Grupos"] },
  {
    id: "40",
    synonymous: ["Oitavas", "Oitavas De Final", "Oitavas De Final "],
  },
  {
    id: "41",
    synonymous: ["Quartas", "Quartas De Final", "Quartas De Final "],
  },
  { id: "42", synonymous: ["Semi", "Semi-Finais", "Semi-Finais "] },
  { id: "43", synonymous: ["Final", "Final "] },
  { id: "44", synonymous: ["1ª Eliminatória"] },
  { id: "45", synonymous: ["2ª Eliminatória"] },
  { id: "46", synonymous: ["3ª Eliminatória", "3ª Eliminatória "] },
  { id: "47", synonymous: ["4ª Eliminatória "] },
];

module.exports = championshipRoundsIds;
