const stadiumsIds = [
  { id: "1", synonymous: ["Estádio Beira-Rio", "Beira-Rio"] },
  { id: "2", synonymous: ["Allianz Parque"] },
  { id: "3", synonymous: ["Altos da Glória"] },
  { id: "4", synonymous: ["Arena Acreana"] },
  { id: "5", synonymous: ["Arena Barueri"] },
  { id: "6", synonymous: ["Arena Cajueiro"] },
  { id: "7", synonymous: ["Arena Condá"] },
  { id: "8", synonymous: ["Arena Fonte Nova"] },
  { id: "9", synonymous: ["Arena Joinville"] },
  { id: "10", synonymous: ["Arena MRV"] },
  { id: "11", synonymous: ["Arena Pantanal"] },
  { id: "12", synonymous: ["Arena da Amazônia", "Arena da Amazonia"] },
  { id: "13", synonymous: ["Arena da Baixada"] },
  { id: "14", synonymous: ["Arena das Dunas"] },
  { id: "15", synonymous: ["Arena de Pernambuco"] },
  { id: "16", synonymous: ["Arena do Grêmio", "Arena"] },
  { id: "17", synonymous: ["Campus Realzale Gazteak"] },
  { id: "18", synonymous: ["Estadio Municipal Passo das Emas"] },
  { id: "19", synonymous: ["Estadio Parque Maracaná"] },
  { id: "20", synonymous: ["Estádio 19 de Outubro"] },
  { id: "21", synonymous: ["Estádio Adauto Moraes"] },
  { id: "22", synonymous: ["Estádio Adelmar da Costa Carvalho"] },
  { id: "23", synonymous: ["Estádio Aderbal Ramos da Silva"] },
  { id: "24", synonymous: ["Estádio Alberto Oliveira"] },
  { id: "25", synonymous: ["Estádio Alfredo Jaconi"] },
  { id: "26", synonymous: ["Estádio Alfredo Jaconi"] },
  { id: "27", synonymous: ["Estádio Aniceto Moscoso"] },
  { id: "28", synonymous: ["Estádio Antonio Accioly"] },
  { id: "29", synonymous: ["Estádio Antônio Aquino Lopes"] },
  { id: "30", synonymous: ["Estádio Antônio Guimarães de Almeida"] },
  { id: "31", synonymous: ["Estádio Arnaldo Lopes Martins"] },
  { id: "32", synonymous: ["Estádio Augusto Bauer"] },
  { id: "33", synonymous: ["Estádio Barão da Serra Negra"] },
  { id: "34", synonymous: ["Estádio Benedito Teixeira"] },
  { id: "35", synonymous: ["Estádio Bento Mendes de Freitas"] },
  { id: "36", synonymous: ["Estádio Brinco de Ouro da Princesa"] },
  { id: "37", synonymous: ["Estádio Bruno José Daniel"] },
  { id: "38", synonymous: ["Estádio Cláudio Moacyr de Azevedo"] },
  { id: "39", synonymous: ["Estádio Cornélio de Barros"] },
  { id: "40", synonymous: ["Estádio Cícero Pompeu de Toledo"] },
  { id: "41", synonymous: ["Estádio Doutor Adhemar de Barros"] },
  { id: "42", synonymous: ["Estádio Doutor Getúlio Dornelles Vargas"] },
  { id: "43", synonymous: ["Estádio Doutor Hercílio Luz"] },
  { id: "44", synonymous: ["Estádio Doutor Osvaldo Texeira Duarte"] },
  { id: "45", synonymous: ["Estádio Doutor Ronaldo Junqueira"] },
  { id: "46", synonymous: ["Estádio Durival Britto e Silva"] },
  { id: "47", synonymous: ["Estádio Elcyr Resende de Mendonça"] },
  { id: "48", synonymous: ["Estádio Elmo Serejo Farias"] },
  { id: "49", synonymous: ["Estádio Eládio de Barros Carvalho"] },
  {
    id: "50",
    synonymous: ["Estádio Estadual Jornalista Edgar Augusto Proença"],
  },
  { id: "51", synonymous: ["Estádio Estadual Kléber José de Andrade"] },
  { id: "52", synonymous: ["Estádio Estadual Lourival Baptista"] },
  { id: "53", synonymous: ["Estádio Evandro Almeida"] },
  { id: "54", synonymous: ["Estádio Flamarion Vasconcelos"] },
  {
    id: "55",
    synonymous: [
      "Estádio Francisco Novelletto Neto",
      "Estádio passo d'areia",
      "São José",
    ],
  },
  { id: "56", synonymous: ["Estádio Francisco Stédile"] },
  { id: "57", synonymous: ["Estádio Francisco Vasques"] },
  {
    id: "58",
    synonymous: [
      "Estádio Frei Epifânio DAbadia",
      "Estádio Frei Epifânio D'Abadia",
    ],
  },
  { id: "59", synonymous: ["Estádio General Sylvio Raulino de Oliveira"] },
  { id: "60", synonymous: ["Estádio General Sílvio Raulino de Oliveira"] },
  { id: "61", synonymous: ["Estádio Germano Kruger"] },
  { id: "62", synonymous: ["Estádio Giulite Coutinho"] },
  { id: "63", synonymous: ["Estádio Governador Alberto Tavares Silva"] },
  { id: "64", synonymous: ["Estádio Governador João Castelo - Castelão"] },
  { id: "65", synonymous: ["Estádio Governador Magalhães Pinto"] },
  { id: "66", synonymous: ["Estádio Governador Plácido Castelo"] },
  { id: "67", synonymous: ["Estádio Governador Roberto Santos"] },
  { id: "68", synonymous: ["Estádio Heriberto Hülse"] },
  { id: "69", synonymous: ["Estádio Iliê Vidal"] },
  { id: "70", synonymous: ["Estádio Ismael Benigno"] },
  { id: "71", synonymous: ["Estádio Jacques da Luz"] },
  { id: "72", synonymous: ["Estádio Joaquim Henrique Nogueira"] },
  { id: "73", synonymous: ["Estádio Joaquim Portugal"] },
  { id: "74", synonymous: ["Estádio Jonas Ferreira Duarte"] },
  { id: "75", synonymous: ["Estádio Jorge Ismael de Biasi"] },
  { id: "76", synonymous: ["Estádio Jornalista Mário Filho"] },
  { id: "77", synonymous: ["Estádio José Gomes da Costa"] },
  { id: "78", synonymous: ["Estádio José Mammoud Abbas"] },
  { id: "79", synonymous: ["Estádio José Olimpio da Rocha"] },
  { id: "80", synonymous: ["Estádio José Roriz Aguiar"] },
  { id: "81", synonymous: ["Estádio José do Rego Maciel"] },
  { id: "82", synonymous: ["Estádio João Cláudio de Vasconcelos Machado"] },
  { id: "83", synonymous: ["Estádio Jânio Moraes"] },
  { id: "84", synonymous: ["Estádio Leandro Cláudio da Silva"] },
  { id: "85", synonymous: ["Estádio Leônidas Sodré de Castro"] },
  { id: "86", synonymous: ["Estádio Lindolfo Monteiro"] },
  { id: "87", synonymous: ["Estádio Luso Brasileiro"] },
  { id: "88", synonymous: ["Estádio Lírio Callou"] },
  { id: "89", synonymous: ["Estádio Major Antônio Couto Pereira"] },
  { id: "90", synonymous: ["Estádio Manoel Barradas"] },
  { id: "91", synonymous: ["Estádio Manoel Dantas Barreto"] },
  { id: "92", synonymous: ["Estádio Maria Lamas Farache"] },
  { id: "93", synonymous: ["Estádio Maria de Lourdes Abadia"] },
  { id: "94", synonymous: ["Estádio Mauro Sampaio"] },
  { id: "95", synonymous: ["Estádio Maximino Porpino Filho"] },
  { id: "96", synonymous: ["Estádio Milton de Souza Corrêa"] },
  { id: "97", synonymous: ["Estádio Moisés Lucarelli"] },
  { id: "98", synonymous: ["Estádio Municipal 14 de Dezembro"] },
  { id: "99", synonymous: ["Estádio Municipal Aluízio Pinheiro Ferreira"] },
  { id: "100", synonymous: ["Estádio Municipal Anacleto Campanella"] },
  { id: "101", synonymous: ["Estádio Municipal Antônio Dias"] },
  {
    id: "102",
    synonymous: ["Estádio Municipal Antônio de Figueiredo Carneiro"],
  },
  { id: "103", synonymous: ["Estádio Municipal Bento de Abreu Sampaio Vidal"] },
  { id: "104", synonymous: ["Estádio Municipal Coaracy da Mata Fonseca"] },
  { id: "105", synonymous: ["Estádio Municipal Doutor Novelli Júnior"] },
  { id: "106", synonymous: ["Estádio Municipal Dr. Rafael Seabra"] },
  { id: "107", synonymous: ["Estádio Municipal Eduardo José Farah"] },
  { id: "108", synonymous: ["Estádio Municipal Engenheiro Luthero Lopes"] },
  { id: "109", synonymous: ["Estádio Municipal Felipe Raulino"] },
  { id: "110", synonymous: ["Estádio Municipal Gentil Valério"] },
  { id: "111", synonymous: ["Estádio Municipal Gerson do Amaral"] },
  { id: "112", synonymous: ["Estádio Municipal Governador Antônio Mariz"] },
  { id: "113", synonymous: ["Estádio Municipal Helvídio Nunes de Barros"] },
  { id: "114", synonymous: ["Estádio Municipal Irmão Gino Maria Rossi"] },
  { id: "115", synonymous: ["Estádio Municipal Jacy Scaff"] },
  { id: "116", synonymous: ["Estádio Municipal Jairton Menezes de Mendonça"] },
  { id: "117", synonymous: ["Estádio Municipal José María de Campos Maia"] },
  { id: "118", synonymous: ["Estádio Municipal João Lamego Netto"] },
  { id: "119", synonymous: ["Estádio Municipal Marcos Pinheiro Neto"] },
  { id: "120", synonymous: ["Estádio Municipal Nhozinho Santos"] },
  { id: "121", synonymous: ["Estádio Municipal Parque do Sabiá"] },
  { id: "122", synonymous: ["Estádio Municipal Paulo Machado de Carvalho"] },
  { id: "123", synonymous: ["Estádio Municipal Pedro Alelaf"] },
  { id: "124", synonymous: ["Estádio Municipal Plácido Aderaldo Castelo"] },
  { id: "125", synonymous: ["Estádio Municipal Prefeito Dilzon Luiz de Melo"] },
  { id: "126", synonymous: ["Estádio Municipal Radialista Mário Helênio"] },
  { id: "127", synonymous: ["Estádio Municipal Raimundo de Oliveira"] },
  { id: "128", synonymous: ["Estádio Municipal Roberto Santos Garcia"] },
  { id: "129", synonymous: ["Estádio Municipal Valdir Doilho Wons"] },
  {
    id: "130",
    synonymous: [
      "Estádio Municipal Vereador Benedito Laurindo de Souza ou Estádio Dito",
    ],
  },
  { id: "131", synonymous: ["Estádio Municipal Zinho de Oliveira"] },
  { id: "132", synonymous: ["Estádio Mário Pinto de Souza"] },
  { id: "133", synonymous: ["Estádio Nabi Abi Chedid"] },
  { id: "134", synonymous: ["Estádio Nacional de Brasília Mané Garrincha"] },
  { id: "135", synonymous: ["Estádio Nilton Santos"] },
  { id: "136", synonymous: ["Estádio Olimpico Albino Turbay"] },
  {
    id: "137",
    synonymous: [
      "Estádio Olímpico Colosso da Lagoa",
      "Colosso da Lagoa",
      "Colosso da Lagoa – Erechim",
      "Colosso da Lagoa, em Erechim",
      "Colosso da Lagoa, Erechim",
    ],
  },
  { id: "138", synonymous: ["Estádio Olímpico Monumental", "Olímpico"] },
  { id: "139", synonymous: ["Estádio Olímpico Municipal Gilberto Mestrinho"] },
  { id: "140", synonymous: ["Estádio Olímpico Nilton Santos"] },
  { id: "141", synonymous: ["Estádio Olímpico Pedro Ludovico Teixeira"] },
  { id: "142", synonymous: ["Estádio Olímpico Regional Arnaldo Busatto"] },
  { id: "143", synonymous: ["Estádio Olímpio Perim"] },
  { id: "144", synonymous: ["Estádio Onésio Brasileiro Alvarenga"] },
  { id: "145", synonymous: ["Estádio Orlando Scarpelli"] },
  { id: "146", synonymous: ["Estádio Paulo Barreto de Menezes"] },
  { id: "147", synonymous: ["Estádio Paulo Constantino"] },
  { id: "148", synonymous: ["Estádio Presidente Vargas"] },
  { id: "149", synonymous: ["Estádio Primeiro de Maio"] },
  { id: "150", synonymous: ["Estádio Proletário Guilherme da Silveira"] },
  { id: "151", synonymous: ["Estádio Raimundo Sampaio"] },
  { id: "152", synonymous: ["Estádio Regional Willie Davids"] },
  { id: "153", synonymous: ["Estádio Rei Pelé"] },
  { id: "154", synonymous: ["Estádio Renato Cunha Lima"] },
  { id: "155", synonymous: ["Estádio Salvador Venâncio da Costa"] },
  { id: "156", synonymous: ["Estádio Santa Cruz"] },
  { id: "157", synonymous: ["Estádio Senador João Ribeiro"] },
  { id: "158", synonymous: ["Estádio Serra Dourada"] },
  { id: "159", synonymous: ["Estádio Soares de Azevedo"] },
  { id: "160", synonymous: ["Estádio São Benedito"] },
  { id: "161", synonymous: ["Estádio São Januário"] },
  { id: "162", synonymous: ["Estádio Universitário Pedro Pedrossian"] },
  { id: "163", synonymous: ["Estádio Urbano Caldeira"] },
  { id: "164", synonymous: ["Estádio Vail Chaves"] },
  { id: "165", synonymous: ["Estádio Valdeir José de Oliveira"] },
  { id: "166", synonymous: ["Estádio Valmir Campelo Bezerra"] },
  { id: "167", synonymous: ["Estádio Vianão"] },
  { id: "168", synonymous: ["Estádio Zama Maciel"] },
  { id: "169", synonymous: ["Estádio Zenor Pedrosa Rocha"] },
  { id: "170", synonymous: ["Estádio de Hailé Pinheiro"] },
  { id: "171", synonymous: ["Estádio de Los Larios"] },
  { id: "172", synonymous: ["Estádio do Governo do Estado de Goiás"] },
  { id: "173", synonymous: ["Estádio do Trabalhador"] },
  { id: "174", synonymous: ["Estádio do Vale"] },
  { id: "175", synonymous: ["Estádio dos Plátanos"] },
  { id: "176", synonymous: ["Estádio Érton Coelho de Queiroz"] },
  { id: "177", synonymous: ["Itaipava Arena Pernambuco"] },
  { id: "178", synonymous: ["Laerte Pais Coelho"] },
  { id: "179", synonymous: ["Ligga Arena"] },
  { id: "180", synonymous: ["Morenão"] },
  { id: "181", synonymous: ["Neo Química Arena"] },
  { id: "182", synonymous: ["Os Pioneiros"] },
  { id: "183", synonymous: ["Pinheirão"] },
  {
    id: "185",
    synonymous: [
      "Estádio Centenário",
      "Centenário",
      "Centenário (Caxias do Sul)",
    ],
  },
  { id: "186", synonymous: ["Atílio Paiva", "Atílio Paiva (Rivera, Uruguai)"] },
  {
    id: "187",
    synonymous: [
      "Montanha dos Vinhedos",
      "Montanha",
      "Montanha dos Vinhedos – Bento Gonçalves",
    ],
  },
  { id: "188", synonymous: ["Estádio dos Eucaliptos", "Eucaliptos"] },
  {
    id: "189",
    synonymous: ["Estádio da Baixada Rubra", "Baixada Rubra – Caxias do Sul"],
  },
  {
    id: "190",
    synonymous: ["Estádio da Chácara dos Eucaliptos", "Chácara dos Eucaliptos"],
  },
  {
    id: "191",
    synonymous: ["Estádio da Chácara das Camélias", "Chácara das Camélias"],
  },
  { id: "192", synonymous: ["Campo da Escola de Guerra", "Escola Guerra"] },
  { id: "193", synonymous: ["Estádio da Baixada", "Baixada"] },
  { id: "194", synonymous: ["Estádio da Timbaúva", "Timbaúva"] },
  { id: "195", synonymous: ["Estádio Tiradentes", "Tiradentes"] },
  { id: "196", synonymous: ["Estádio Aldo Dapuzzo", "Rio Grande"] },
  { id: "197", synonymous: ["Estádio dos Plátanos", "Santa Cruz"] },
];

module.exports = stadiumsIds;
