const teamsIds = [
  { id: "1", synonymous: ["Inter", "Internacional"] },
  { id: "2", synonymous: ["Botafogo"] },
  { id: "3", synonymous: ["Bragantino", "RB Bragantino"] },
  { id: "4", synonymous: ["Palmeiras"] },
  { id: "5", synonymous: ["Flamengo"] },
  { id: "6", synonymous: ["Athletico-PR", "Atlético-PR"] },
  { id: "7", synonymous: ["Grêmio"] },
  { id: "8", synonymous: ["Atlético-MG"] },
  { id: "9", synonymous: ["Fluminense"] },
  { id: "10", synonymous: ["Fortaleza"] },
  { id: "11", synonymous: ["São Paulo"] },
  { id: "12", synonymous: ["Cuiabá", "Cuiabá-MT"] },
  { id: "13", synonymous: ["Cruzeiro"] },
  { id: "14", synonymous: ["Corinthians"] },
  { id: "15", synonymous: ["Bahia", "EC Bahia"] },
  { id: "16", synonymous: ["Santos", "Santos FC"] },
  { id: "17", synonymous: ["Goiás", "Goiás EC"] },
  { id: "18", synonymous: ["Vasco da Gama"] },
  { id: "19", synonymous: ["Coritiba", "Coritiba FC"] },
  { id: "20", synonymous: ["América-MG"] },
  { id: "21", synonymous: ["Ceará SC"] },
  { id: "22", synonymous: ["Atlético-GO"] },
  { id: "23", synonymous: ["Sport Recife"] },
  { id: "24", synonymous: ["Santo André"] },
  { id: "25", synonymous: ["EC Vitória"] },
  { id: "26", synonymous: ["Náutico"] },
  { id: "27", synonymous: ["Avaí FC"] },
  { id: "28", synonymous: ["Barueri"] },
  { id: "29", synonymous: ["Juventude"] },
  { id: "30", synonymous: ["Chapecoense"] },
  { id: "31", synonymous: ["Figueirense FC"] },
  { id: "32", synonymous: ["Guarani"] },
  { id: "33", synonymous: ["Paraná"] },
  { id: "34", synonymous: ["Ponte Preta"] },
  { id: "35", synonymous: ["São Caetano"] },
  { id: "36", synonymous: ["Santa Cruz"] },
  { id: "37", synonymous: ["América-RN"] },
  { id: "38", synonymous: ["Portuguesa"] },
  { id: "39", synonymous: ["Ipatinga FC"] },
  { id: "40", synonymous: ["CSA"] },
  { id: "41", synonymous: ["Paysandu SC", "Paysandu"] },
  { id: "42", synonymous: ["Criciúma EC"] },
  { id: "43", synonymous: ["Joinville-SC"] },
  { id: "44", synonymous: ["Brasiliense-DF"] },
  { id: "45", synonymous: ["4 de Julho"] },
  { id: "46", synonymous: ["ABC FC"] },
  { id: "47", synonymous: ["AD Bahia-BA"] },
  { id: "48", synonymous: ["ASA"] },
  { id: "49", synonymous: ["Afogados"] },
  { id: "50", synonymous: ["Altos"] },
  { id: "51", synonymous: ["Anápolis"] },
  { id: "52", synonymous: ["Aquidauanense"] },
  { id: "53", synonymous: ["Athletic"] },
  { id: "54", synonymous: ["Atl. Acreano"] },
  { id: "55", synonymous: ["Atl. Alagoinhas"] },
  { id: "56", synonymous: ["Azuriz"] },
  { id: "57", synonymous: ["Bangu-RJ"] },
  { id: "58", synonymous: ["Barbalha"] },
  { id: "59", synonymous: ["Boa Esporte"] },
  { id: "60", synonymous: ["Boavista"] },
  { id: "61", synonymous: ["Botafogo-PB"] },
  { id: "62", synonymous: ["Botafogo-SP"] },
  { id: "63", synonymous: ["Bragantino-PA"] },
  { id: "64", synonymous: ["Brasil Pelotas"] },
  { id: "65", synonymous: ["Brasiliense"] },
  { id: "66", synonymous: ["Brusque"] },
  { id: "67", synonymous: ["CRB"] },
  { id: "68", synonymous: ["Caldense"] },
  { id: "69", synonymous: ["Camboriú"] },
  { id: "70", synonymous: ["Campinense-PB"] },
  { id: "71", synonymous: ["Castanhal"] },
  { id: "72", synonymous: ["Caucaia-CE"] },
  { id: "73", synonymous: ["Caxias-RS"] },
  { id: "74", synonymous: ["Ceilândia"] },
  { id: "75", synonymous: ["Cianorte"] },
  { id: "76", synonymous: ["Confiança"] },
  { id: "77", synonymous: ["Cordino"] },
  { id: "78", synonymous: ["Coruripe"] },
  { id: "79", synonymous: ["Costa Rica"] },
  { id: "80", synonymous: ["Democrata GV"] },
  { id: "81", synonymous: ["EC São José"] },
  { id: "82", synonymous: ["Esportivo"] },
  { id: "83", synonymous: ["FC Cascavel"] },
  { id: "84", synonymous: ["Falcon"] },
  { id: "85", synonymous: ["Fast"] },
  { id: "86", synonymous: ["Ferroviária"] },
  { id: "87", synonymous: ["Ferroviário"] },
  { id: "88", synonymous: ["Fluminense-PI"] },
  { id: "89", synonymous: ["Freipaulistano"] },
  { id: "90", synonymous: ["Galvez"] },
  { id: "91", synonymous: ["Globo"] },
  { id: "92", synonymous: ["Glória"] },
  { id: "93", synonymous: ["Goianésia (GO)"] },
  { id: "94", synonymous: ["Guarany Sobral"] },
  { id: "95", synonymous: ["Humaitá"] },
  { id: "96", synonymous: ["Icasa"] },
  { id: "97", synonymous: ["Iguatu"] },
  { id: "98", synonymous: ["Imperatriz"] },
  { id: "99", synonymous: ["Independente-PA"] },
  { id: "100", synonymous: ["Ituano"] },
  { id: "101", synonymous: ["Jacuipense-BA"] },
  { id: "102", synonymous: ["Jaraguá EC"] },
  { id: "103", synonymous: ["Juazeirense"] },
  { id: "104", synonymous: ["Lagarto"] },
  { id: "105", synonymous: ["Londrina-PR"] },
  { id: "106", synonymous: ["Luverdense"] },
  { id: "107", synonymous: ["Madureira"] },
  { id: "108", synonymous: ["Manaus FC"] },
  { id: "109", synonymous: ["Marcílio Dias"] },
  { id: "110", synonymous: ["Maricá FC"] },
  { id: "111", synonymous: ["Maringá"] },
  { id: "112", synonymous: ["Marília"] },
  { id: "113", synonymous: ["Mirassol-SP"] },
  { id: "114", synonymous: ["Moto Club"] },
  { id: "115", synonymous: ["Murici"] },
  { id: "116", synonymous: ["Nova Iguaçu"] },
  { id: "117", synonymous: ["Nova Mutum"] },
  { id: "118", synonymous: ["Nova Venécia"] },
  { id: "119", synonymous: ["Novo Hamburgo"] },
  { id: "120", synonymous: ["Novorizontino"] },
  { id: "121", synonymous: ["Oeste"] },
  { id: "122", synonymous: ["Operário VG"] },
  { id: "123", synonymous: ["Operário-MS"] },
  { id: "124", synonymous: ["Operário-PR"] },
  { id: "125", synonymous: ["Palmas"] },
  { id: "126", synonymous: ["Parnahyba"] },
  { id: "127", synonymous: ["Peñarol-AM"] },
  { id: "128", synonymous: ["Picos"] },
  { id: "129", synonymous: ["Porto Velho"] },
  { id: "130", synonymous: ["Portuguesa-RJ"] },
  { id: "131", synonymous: ["Pouso Alegre"] },
  { id: "132", synonymous: ["Princesa-AM"] },
  { id: "133", synonymous: ["Real Ariquemes"] },
  { id: "134", synonymous: ["Real Brasília"] },
  { id: "135", synonymous: ["Real Noroeste"] },
  { id: "136", synonymous: ["Remo"] },
  { id: "137", synonymous: ["Resende"] },
  { id: "138", synonymous: ["Retrô"] },
  { id: "139", synonymous: ["Rio Branco VN"] },
  { id: "140", synonymous: ["Rio Branco-AC"] },
  { id: "141", synonymous: ["Rio Branco-ES"] },
  { id: "142", synonymous: ["River-PI"] },
  { id: "143", synonymous: ["SE Gama"] },
  { id: "144", synonymous: ["Salgueiro"] },
  { id: "145", synonymous: ["Sampaio Corrêa"] },
  { id: "146", synonymous: ["Santa Cruz-RS"] },
  { id: "147", synonymous: ["Santos-AP"] },
  { id: "148", synonymous: ["Sergipe"] },
  { id: "149", synonymous: ["Sociedade Esportiva Juventude (MA)"] },
  { id: "150", synonymous: ["Sousa"] },
  { id: "151", synonymous: ["São Bernardo"] },
  { id: "152", synonymous: ["São Francisco"] },
  { id: "153", synonymous: ["São Luiz"] },
  { id: "154", synonymous: ["São Raimundo-AM"] },
  { id: "155", synonymous: ["São Raimundo-RR"] },
  { id: "156", synonymous: ["Tocantinópolis"] },
  { id: "157", synonymous: ["Toledo"] },
  { id: "158", synonymous: ["Tombense"] },
  { id: "159", synonymous: ["Trem"] },
  { id: "160", synonymous: ["Treze"] },
  { id: "161", synonymous: ["Tuna Luso"] },
  { id: "162", synonymous: ["Tuntum"] },
  { id: "163", synonymous: ["U. Rondonópolis"] },
  { id: "164", synonymous: ["UR Trabalhadore"] },
  { id: "165", synonymous: ["Uberlândia"] },
  { id: "166", synonymous: ["União Rond."] },
  { id: "167", synonymous: ["Vila Nova FC"] },
  { id: "168", synonymous: ["Vilhenense"] },
  { id: "169", synonymous: ["Vitória-ES"] },
  { id: "170", synonymous: ["Volta Redonda"] },
  { id: "171", synonymous: ["XV Piracicaba"] },
  { id: "172", synonymous: ["Ypiranga-AP"] },
  { id: "173", synonymous: ["Ypiranga-RS"] },
  { id: "174", synonymous: ["Águia Negra"] },
  { id: "175", synonymous: ["Águia de Marabá"] },
];

module.exports = teamsIds;
