DROP table IF EXISTS game;
DROP table IF EXISTS round;
DROP table IF EXISTS championship;
DROP table IF EXISTS team;
DROP table IF EXISTS stadium;

CREATE TABLE stadium(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name varchar not null,
	nickname varchar null,
    createddate date not null default current_date,
	PRIMARY KEY(id)
);

CREATE TABLE team(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name varchar not null,
	size varchar null,
    createddate date not null default current_date,
	PRIMARY KEY(id)
);

CREATE TABLE championship(
    id varchar not null,
    name varchar not null,
    createddate date not null default current_date,
	PRIMARY KEY(id)
);

CREATE TABLE round(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    round varchar not null,
	createddate date not null default current_date,
	PRIMARY KEY(id)
);

CREATE TABLE game(
    id INT GENERATED BY DEFAULT AS IDENTITY,
	idChampionship varchar not null,
    idRound int not null,
	idStadium int null,
	attendance int null,
	idTeamHome int not null,
	scoreTeamHome int null,
	idTeamAway int not null,
	scoreTeamAway int null,
	gameDate date null,
	gameCanceled boolean default FALSE, 
	createddate date not null default current_date,
	PRIMARY KEY(id),
	CONSTRAINT fk_game_championship FOREIGN KEY (idChampionship) REFERENCES championship (id),
	CONSTRAINT fk_game_round FOREIGN KEY (idRound) REFERENCES round (id),
	CONSTRAINT fk_game_stadium FOREIGN KEY (idStadium) REFERENCES stadium (id),
	CONSTRAINT fk_game_teamHome FOREIGN KEY (idTeamHome) REFERENCES team (id),
	CONSTRAINT fk_game_teamAway FOREIGN KEY (idTeamAway) REFERENCES team (id)
);


insert into championship (id, name) values ('2023_BR', 'Brasileirão 2023');
insert into championship (id, name) values ('2022_BR', 'Brasileirão 2022');
insert into championship (id, name) values ('2021_BR', 'Brasileirão 2021');
insert into championship (id, name) values ('2020_BR', 'Brasileirão 2020');
insert into championship (id, name) values ('2019_BR', 'Brasileirão 2019');
insert into championship (id, name) values ('2018_BR', 'Brasileirão 2018');
insert into championship (id, name) values ('2017_BR', 'Brasileirão 2017');
insert into championship (id, name) values ('2016_BR', 'Brasileirão 2016');
insert into championship (id, name) values ('2015_BR', 'Brasileirão 2015');
insert into championship (id, name) values ('2014_BR', 'Brasileirão 2014');
insert into championship (id, name) values ('2013_BR', 'Brasileirão 2013');
insert into championship (id, name) values ('2012_BR', 'Brasileirão 2012');
insert into championship (id, name) values ('2011_BR', 'Brasileirão 2011');
insert into championship (id, name) values ('2010_BR', 'Brasileirão 2010');
insert into championship (id, name) values ('2009_BR', 'Brasileirão 2009');
insert into championship (id, name) values ('2008_BR', 'Brasileirão 2008');
insert into championship (id, name) values ('2007_BR', 'Brasileirão 2007');
insert into championship (id, name) values ('2006_BR', 'Brasileirão 2006');
insert into championship (id, name) values ('2005_BR', 'Brasileirão 2005');
insert into championship (id, name) values ('2004_BR', 'Brasileirão 2004');
insert into championship (id, name) values ('2003_BR', 'Brasileirão 2003');
insert into championship (id, name) values ('2002_BR', 'Brasileirão 2002');
insert into championship (id, name) values ('2001_BR', 'Brasileirão 2001');
insert into championship (id, name) values ('2000_BR', 'Brasileirão 2000');
insert into championship (id, name) values ('1989_CDB', 'Copa do Brasil 1989');
insert into championship (id, name) values ('1990_CDB', 'Copa do Brasil 1990');
insert into championship (id, name) values ('1991_CDB', 'Copa do Brasil 1991');
insert into championship (id, name) values ('1992_CDB', 'Copa do Brasil 1992');
insert into championship (id, name) values ('1993_CDB', 'Copa do Brasil 1993');
insert into championship (id, name) values ('1994_CDB', 'Copa do Brasil 1994');
insert into championship (id, name) values ('1995_CDB', 'Copa do Brasil 1995');
insert into championship (id, name) values ('1996_CDB', 'Copa do Brasil 1996');
insert into championship (id, name) values ('1997_CDB', 'Copa do Brasil 1997');
insert into championship (id, name) values ('1998_CDB', 'Copa do Brasil 1998');
insert into championship (id, name) values ('1999_CDB', 'Copa do Brasil 1999');
insert into championship (id, name) values ('2000_CDB', 'Copa do Brasil 2000');
insert into championship (id, name) values ('2001_CDB', 'Copa do Brasil 2001');
insert into championship (id, name) values ('2002_CDB', 'Copa do Brasil 2002');
insert into championship (id, name) values ('2003_CDB', 'Copa do Brasil 2003');
insert into championship (id, name) values ('2004_CDB', 'Copa do Brasil 2004');
insert into championship (id, name) values ('2005_CDB', 'Copa do Brasil 2005');
insert into championship (id, name) values ('2006_CDB', 'Copa do Brasil 2006');
insert into championship (id, name) values ('2007_CDB', 'Copa do Brasil 2007');
insert into championship (id, name) values ('2008_CDB', 'Copa do Brasil 2008');
insert into championship (id, name) values ('2009_CDB', 'Copa do Brasil 2009');
insert into championship (id, name) values ('2010_CDB', 'Copa do Brasil 2010');
insert into championship (id, name) values ('2011_CDB', 'Copa do Brasil 2011');
insert into championship (id, name) values ('2012_CDB', 'Copa do Brasil 2012');
insert into championship (id, name) values ('2013_CDB', 'Copa do Brasil 2013');
insert into championship (id, name) values ('2014_CDB', 'Copa do Brasil 2014');
insert into championship (id, name) values ('2015_CDB', 'Copa do Brasil 2015');
insert into championship (id, name) values ('2016_CDB', 'Copa do Brasil 2016');
insert into championship (id, name) values ('2017_CDB', 'Copa do Brasil 2017');
insert into championship (id, name) values ('2018_CDB', 'Copa do Brasil 2018');
insert into championship (id, name) values ('2019_CDB', 'Copa do Brasil 2019');
insert into championship (id, name) values ('2020_CDB', 'Copa do Brasil 2020');
insert into championship (id, name) values ('2021_CDB', 'Copa do Brasil 2021');
insert into championship (id, name) values ('2022_CDB', 'Copa do Brasil 2022');
insert into championship (id, name) values ('2023_CDB', 'Copa do Brasil 2023');


insert into team (id, size, name) values (1, 'X', 'Internacional');
insert into team (id, size, name) values (2, 'M', 'Botafogo');
insert into team (id, size, name) values (3, 'M', 'Bragantino'); 
insert into team (id, size, name) values (4, 'X', 'Palmeiras');
insert into team (id, size, name) values (5, 'X', 'Flamengo');	
insert into team (id, size, name) values (6, 'M', 'Athletico-PR');	
insert into team (id, size, name) values (7, 'X', 'Grêmio');	
insert into team (id, size, name) values (8, 'X', 'Atlético-MG');
insert into team (id, size, name) values (9, 'M', 'Fluminense');	
insert into team (id, size, name) values (10, 'M', 'Fortaleza');	
insert into team (id, size, name) values (11, 'X', 'São Paulo');		
insert into team (id, size, name) values (12, 'S', 'Cuiabá'); 
insert into team (id, size, name) values (13, 'X', 'Cruzeiro');
insert into team (id, size, name) values (14, 'X', 'Corinthians');	
insert into team (id, size, name) values (15, 'M', 'Bahia'); 
insert into team (id, size, name) values (16, 'X', 'Santos');
insert into team (id, size, name) values (17, 'M', 'Goiás');	
insert into team (id, size, name) values (18, 'M', 'Vasco da Gama');
insert into team (id, size, name) values (19, 'M', 'Coritiba');
insert into team (id, size, name) values (20, 'S', 'América-MG');
insert into team (id, size, name) values (21, 'M', 'Ceará SC');
insert into team (id, size, name) values (22, 'M', 'Atlético-GO');
insert into team (id, size, name) values (23, 'M', 'Sport Recife');
insert into team (id, size, name) values (24, 'S', 'Santo André');
insert into team (id, size, name) values (25, 'M', 'EC Vitória');
insert into team (id, size, name) values (26, 'M', 'Náutico');
insert into team (id, size, name) values (27, 'M', 'Avaí FC');
insert into team (id, size, name) values (28, 'S', 'Barueri');
insert into team (id, size, name) values (29, 'M', 'Juventude');
insert into team (id, size, name) values (30, 'M', 'Chapecoense');
insert into team (id, size, name) values (31, 'M', 'Figueirense FC');
insert into team (id, size, name) values (32, 'M', 'Guarani');
insert into team (id, size, name) values (33, 'M', 'Paraná');
insert into team (id, size, name) values (34, 'M', 'Ponte Preta');
insert into team (id, size, name) values (35, 'M', 'São Caetano');
insert into team (id, size, name) values (36, 'S', 'Santa Cruz');
insert into team (id, size, name) values (37, 'S', 'América-RN');
insert into team (id, size, name) values (38, 'M', 'Portuguesa');
insert into team (id, size, name) values (39, 'S', 'Ipatinga FC');
insert into team (id, size, name) values (40, 'S', 'CSA');
insert into team (id, size, name) values (41, 'M', 'Paysandu SC');
insert into team (id, size, name) values (42, 'S', 'Criciúma EC');
insert into team (id, size, name) values (43, 'S', 'Joinville-SC');
insert into team (id, size, name) values (44, 'S', 'Brasiliense-DF');
insert into team (id, size, name) values (	45	,	'S', '4 de Julho');
insert into team (id, size, name) values (	46	,	'S', 'ABC FC');
insert into team (id, size, name) values (	47	,	'S', 'AD Bahia-BA');
insert into team (id, size, name) values (	48	,	'S', 'ASA');
insert into team (id, size, name) values (	49	,	'S', 'Afogados');
insert into team (id, size, name) values (	50	,	'S', 'Altos');
insert into team (id, size, name) values (	51	,	'S', 'Anápolis');
insert into team (id, size, name) values (	52	,	'S', 'Aquidauanense');
insert into team (id, size, name) values (	53	,	'S', 'Athletic');
insert into team (id, size, name) values (	54	,	'S', 'Atl. Acreano');
insert into team (id, size, name) values (	55	,	'S', 'Atl. Alagoinhas');
insert into team (id, size, name) values (	56	,	'S', 'Azuriz');
insert into team (id, size, name) values (	57	,	'S', 'Bangu-RJ');
insert into team (id, size, name) values (	58	,	'S', 'Barbalha');
insert into team (id, size, name) values (	59	,	'S', 'Boa Esporte');
insert into team (id, size, name) values (	60	,	'S', 'Boavista');
insert into team (id, size, name) values (	61	,	'S', 'Botafogo-PB');
insert into team (id, size, name) values (	62	,	'S', 'Botafogo-SP');
insert into team (id, size, name) values (	63	,	'S', 'Bragantino-PA');
insert into team (id, size, name) values (	64	,	'S', 'Brasil Pelotas');
insert into team (id, size, name) values (	65	,	'S', 'Brasiliense');
insert into team (id, size, name) values (	66	,	'S', 'Brusque');
insert into team (id, size, name) values (	67	,	'S', 'CRB');
insert into team (id, size, name) values (	68	,	'S', 'Caldense');
insert into team (id, size, name) values (	69	,	'S', 'Camboriú');
insert into team (id, size, name) values (	70	,	'S', 'Campinense-PB');
insert into team (id, size, name) values (	71	,	'S', 'Castanhal');
insert into team (id, size, name) values (	72	,	'S', 'Caucaia-CE');
insert into team (id, size, name) values (	73	,	'S', 'Caxias-RS');
insert into team (id, size, name) values (	74	,	'S', 'Ceilândia');
insert into team (id, size, name) values (	75	,	'S', 'Cianorte');
insert into team (id, size, name) values (	76	,	'S', 'Confiança');
insert into team (id, size, name) values (	77	,	'S', 'Cordino');
insert into team (id, size, name) values (	78	,	'S', 'Coruripe');
insert into team (id, size, name) values (	79	,	'S', 'Costa Rica');
insert into team (id, size, name) values (	80	,	'S', 'Democrata GV');
insert into team (id, size, name) values (	81	,	'S', 'EC São José');
insert into team (id, size, name) values (	82	,	'S', 'Esportivo');
insert into team (id, size, name) values (	83	,	'S', 'FC Cascavel');
insert into team (id, size, name) values (	84	,	'S', 'Falcon');
insert into team (id, size, name) values (	85	,	'S', 'Fast');
insert into team (id, size, name) values (	86	,	'S', 'Ferroviária');
insert into team (id, size, name) values (	87	,	'S', 'Ferroviário');
insert into team (id, size, name) values (	88	,	'S', 'Fluminense-PI');
insert into team (id, size, name) values (	89	,	'S', 'Freipaulistano');
insert into team (id, size, name) values (	90	,	'S', 'Galvez');
insert into team (id, size, name) values (	91	,	'S', 'Globo');
insert into team (id, size, name) values (	92	,	'S', 'Glória');
insert into team (id, size, name) values (	93	,	'S', 'Goianésia (GO)');
insert into team (id, size, name) values (	94	,	'S', 'Guarany Sobral');
insert into team (id, size, name) values (	95	,	'S', 'Humaitá');
insert into team (id, size, name) values (	96	,	'S', 'Icasa');
insert into team (id, size, name) values (	97	,	'S', 'Iguatu');
insert into team (id, size, name) values (	98	,	'S', 'Imperatriz');
insert into team (id, size, name) values (	99	,	'S', 'Independente-PA');
insert into team (id, size, name) values (	100	,	'S', 'Ituano');
insert into team (id, size, name) values (	101	,	'S', 'Jacuipense-BA');
insert into team (id, size, name) values (	102	,	'S', 'Jaraguá EC');
insert into team (id, size, name) values (	103	,	'S', 'Juazeirense');
insert into team (id, size, name) values (	104	,	'S', 'Lagarto');
insert into team (id, size, name) values (	105	,	'S', 'Londrina-PR');
insert into team (id, size, name) values (	106	,	'S', 'Luverdense');
insert into team (id, size, name) values (	107	,	'S', 'Madureira');
insert into team (id, size, name) values (	108	,	'S', 'Manaus FC');
insert into team (id, size, name) values (	109	,	'S', 'Marcílio Dias');
insert into team (id, size, name) values (	110	,	'S', 'Maricá FC');
insert into team (id, size, name) values (	111	,	'S', 'Maringá');
insert into team (id, size, name) values (	112	,	'S', 'Marília');
insert into team (id, size, name) values (	113	,	'S', 'Mirassol-SP');
insert into team (id, size, name) values (	114	,	'S', 'Moto Club');
insert into team (id, size, name) values (	115	,	'S', 'Murici');
insert into team (id, size, name) values (	116	,	'S', 'Nova Iguaçu');
insert into team (id, size, name) values (	117	,	'S', 'Nova Mutum');
insert into team (id, size, name) values (	118	,	'S', 'Nova Venécia');
insert into team (id, size, name) values (	119	,	'S', 'Novo Hamburgo');
insert into team (id, size, name) values (	120	,	'S', 'Novorizontino');
insert into team (id, size, name) values (	121	,	'S', 'Oeste');
insert into team (id, size, name) values (	122	,	'S', 'Operário VG');
insert into team (id, size, name) values (	123	,	'S', 'Operário-MS');
insert into team (id, size, name) values (	124	,	'S', 'Operário-PR');
insert into team (id, size, name) values (	125	,	'S', 'Palmas');
insert into team (id, size, name) values (	126	,	'S', 'Parnahyba');
insert into team (id, size, name) values (	127	,	'S', 'Peñarol-AM');
insert into team (id, size, name) values (	128	,	'S', 'Picos');
insert into team (id, size, name) values (	129	,	'S', 'Porto Velho');
insert into team (id, size, name) values (	130	,	'S', 'Portuguesa-RJ');
insert into team (id, size, name) values (	131	,	'S', 'Pouso Alegre');
insert into team (id, size, name) values (	132	,	'S', 'Princesa-AM');
insert into team (id, size, name) values (	133	,	'S', 'Real Ariquemes');
insert into team (id, size, name) values (	134	,	'S', 'Real Brasília');
insert into team (id, size, name) values (	135	,	'S', 'Real Noroeste');
insert into team (id, size, name) values (	136	,	'S', 'Remo');
insert into team (id, size, name) values (	137	,	'S', 'Resende');
insert into team (id, size, name) values (	138	,	'S', 'Retrô');
insert into team (id, size, name) values (	139	,	'S', 'Rio Branco VN');
insert into team (id, size, name) values (	140	,	'S', 'Rio Branco-AC');
insert into team (id, size, name) values (	141	,	'S', 'Rio Branco-ES');
insert into team (id, size, name) values (	142	,	'S', 'River-PI');
insert into team (id, size, name) values (	143	,	'S', 'SE Gama');
insert into team (id, size, name) values (	144	,	'S', 'Salgueiro');
insert into team (id, size, name) values (	145	,	'S', 'Sampaio Corrêa');
insert into team (id, size, name) values (	146	,	'S', 'Santa Cruz-RS');
insert into team (id, size, name) values (	147	,	'S', 'Santos-AP');
insert into team (id, size, name) values (	148	,	'S', 'Sergipe');
insert into team (id, size, name) values (	149	,	'S', 'Sociedade Esportiva Juventude (MA)');
insert into team (id, size, name) values (	150	,	'S', 'Sousa');
insert into team (id, size, name) values (	151	,	'S', 'São Bernardo');
insert into team (id, size, name) values (	152	,	'S', 'São Francisco');
insert into team (id, size, name) values (	153	,	'S', 'São Luiz');
insert into team (id, size, name) values (	154	,	'S', 'São Raimundo-AM');
insert into team (id, size, name) values (	155	,	'S', 'São Raimundo-RR');
insert into team (id, size, name) values (	156	,	'S', 'Tocantinópolis');
insert into team (id, size, name) values (	157	,	'S', 'Toledo');
insert into team (id, size, name) values (	158	,	'S', 'Tombense');
insert into team (id, size, name) values (	159	,	'S', 'Trem');
insert into team (id, size, name) values (	160	,	'S', 'Treze');
insert into team (id, size, name) values (	161	,	'S', 'Tuna Luso');
insert into team (id, size, name) values (	162	,	'S', 'Tuntum');
insert into team (id, size, name) values (	163	,	'S', 'U. Rondonópolis');
insert into team (id, size, name) values (	164	,	'S', 'UR Trabalhadore');
insert into team (id, size, name) values (	165	,	'S', 'Uberlândia');
insert into team (id, size, name) values (	166	,	'S', 'União Rond.');
insert into team (id, size, name) values (	167	,	'S', 'Vila Nova FC');
insert into team (id, size, name) values (	168	,	'S', 'Vilhenense');
insert into team (id, size, name) values (	169	,	'S', 'Vitória-ES');
insert into team (id, size, name) values (	170	,	'S', 'Volta Redonda');
insert into team (id, size, name) values (	171	,	'S', 'XV Piracicaba');
insert into team (id, size, name) values (	172	,	'S', 'Ypiranga-AP');
insert into team (id, size, name) values (	173	,	'S', 'Ypiranga-RS');
insert into team (id, size, name) values (	174	,	'S', 'Águia Negra');
insert into team (id, size, name) values (	175	,	'S', 'Águia de Marabá');



insert into round (id, round) values (1, '1');
insert into round (id, round) values (2, '2');
insert into round (id, Round) values (3, '3');
insert into round (id, Round) values (4, '4');
insert into round (id, Round) values (5, '5');
insert into round (id, Round) values (6, '6');
insert into round (id, Round) values (7, '7');
insert into round (id, Round) values (8, '8');
insert into round (id, Round) values (9, '9');
insert into round (id, Round) values (10, '10');
insert into round (id, Round) values (11, '11');
insert into round (id, Round) values (12, '12');
insert into round (id, Round) values (13, '13');
insert into round (id, Round) values (14, '14');
insert into round (id, Round) values (15, '15');
insert into round (id, Round) values (16, '16');
insert into round (id, Round) values (17, '17');
insert into round (id, Round) values (18, '18');
insert into round (id, Round) values (19, '19');
insert into round (id, Round) values (20, '20');
insert into round (id, Round) values (21, '21');
insert into round (id, Round) values (22, '22');
insert into round (id, Round) values (23, '23');
insert into round (id, Round) values (24, '24');
insert into round (id, Round) values (25, '25');
insert into round (id, Round) values (26, '26');
insert into round (id, Round) values (27, '27');
insert into round (id, Round) values (28, '28');
insert into round (id, Round) values (29, '29');
insert into round (id, Round) values (30, '30');
insert into round (id, Round) values (31, '31');
insert into round (id, Round) values (32, '32');
insert into round (id, Round) values (33, '33');
insert into round (id, Round) values (34, '34');
insert into round (id, Round) values (35, '35');
insert into round (id, Round) values (36, '36');
insert into round (id, Round) values (37, '37');
insert into round (id, Round) values (38, '38');
insert into round (id, Round) values (39, 'Grupos');
insert into round (id, Round) values (40, 'Oitavas');
insert into round (id, Round) values (41, 'Quartas');
insert into round (id, Round) values (42, 'Semi');
insert into round (id, Round) values (43, 'Final');
insert into round (id, Round) values (44, '1ª Eliminatória');
insert into round (id, Round) values (45, '2ª Eliminatória');
insert into round (id, Round) values (46, '3ª Eliminatória');
insert into round (id, Round) values (47, '4ª Eliminatória');

insert into stadium (id, name) values (1, 'Estádio Beira-Rio');
insert into stadium (id, name) values (2, 'Allianz Parque');
insert into stadium (id, name) values (3, 'Altos da Glória');
insert into stadium (id, name) values (4, 'Arena Acreana');
insert into stadium (id, name) values (5, 'Arena Barueri');
insert into stadium (id, name) values (6, 'Arena Cajueiro');
insert into stadium (id, name) values (7, 'Arena Condá');
insert into stadium (id, name) values (8, 'Arena Fonte Nova');
insert into stadium (id, name) values (9, 'Arena Joinville');
insert into stadium (id, name) values (10, 'Arena MRV');
insert into stadium (id, name) values (11, 'Arena Pantanal');
insert into stadium (id, name) values (12, 'Arena da Amazônia');
insert into stadium (id, name) values (13, 'Arena da Baixada');
insert into stadium (id, name) values (14, 'Arena das Dunas');
insert into stadium (id, name) values (15, 'Arena de Pernambuco');
insert into stadium (id, name) values (16, 'Arena do Grêmio');
insert into stadium (id, name) values (17, 'Campus Realzale Gazteak');
insert into stadium (id, name) values (18, 'Estadio Municipal Passo das Emas');
insert into stadium (id, name) values (19, 'Estadio Parque Maracaná');
insert into stadium (id, name) values (20, 'Estádio 19 de Outubro');
insert into stadium (id, name) values (21, 'Estádio Adauto Moraes');
insert into stadium (id, name) values (22, 'Estádio Adelmar da Costa Carvalho');
insert into stadium (id, name) values (23, 'Estádio Aderbal Ramos da Silva');
insert into stadium (id, name) values (24, 'Estádio Alberto Oliveira');
insert into stadium (id, name) values (25, 'Estádio Alfredo Jaconi');
insert into stadium (id, name) values (26, 'Estádio Alfredo Jaconi');
insert into stadium (id, name) values (27, 'Estádio Aniceto Moscoso');
insert into stadium (id, name) values (28, 'Estádio Antonio Accioly');
insert into stadium (id, name) values (29, 'Estádio Antônio Aquino Lopes');
insert into stadium (id, name) values (30, 'Estádio Antônio Guimarães de Almeida');
insert into stadium (id, name) values (31, 'Estádio Arnaldo Lopes Martins');
insert into stadium (id, name) values (32, 'Estádio Augusto Bauer');
insert into stadium (id, name) values (33, 'Estádio Barão da Serra Negra');
insert into stadium (id, name) values (34, 'Estádio Benedito Teixeira');
insert into stadium (id, name) values (35, 'Estádio Bento Mendes de Freitas');
insert into stadium (id, name) values (36, 'Estádio Brinco de Ouro da Princesa');
insert into stadium (id, name) values (37, 'Estádio Bruno José Daniel');
insert into stadium (id, name) values (38, 'Estádio Cláudio Moacyr de Azevedo');
insert into stadium (id, name) values (39, 'Estádio Cornélio de Barros');
insert into stadium (id, name) values (40, 'Estádio Cícero Pompeu de Toledo');
insert into stadium (id, name) values (41, 'Estádio Doutor Adhemar de Barros');
insert into stadium (id, name) values (42, 'Estádio Doutor Getúlio Dornelles Vargas');
insert into stadium (id, name) values (43, 'Estádio Doutor Hercílio Luz');
insert into stadium (id, name) values (44, 'Estádio Doutor Osvaldo Texeira Duarte');
insert into stadium (id, name) values (45, 'Estádio Doutor Ronaldo Junqueira');
insert into stadium (id, name) values (46, 'Estádio Durival Britto e Silva');
insert into stadium (id, name) values (47, 'Estádio Elcyr Resende de Mendonça');
insert into stadium (id, name) values (48, 'Estádio Elmo Serejo Farias');
insert into stadium (id, name) values (49, 'Estádio Eládio de Barros Carvalho');
insert into stadium (id, name) values (50, 'Estádio Estadual Jornalista Edgar Augusto Proença');
insert into stadium (id, name) values (51, 'Estádio Estadual Kléber José de Andrade');
insert into stadium (id, name) values (52, 'Estádio Estadual Lourival Baptista');
insert into stadium (id, name) values (53, 'Estádio Evandro Almeida');
insert into stadium (id, name) values (54, 'Estádio Flamarion Vasconcelos');
insert into stadium (id, name) values (55, 'Estádio Francisco Novelletto Neto');
insert into stadium (id, name) values (56, 'Estádio Francisco Stédile');
insert into stadium (id, name) values (57, 'Estádio Francisco Vasques');
insert into stadium (id, name) values (58, 'Estádio Frei Epifânio DAbadia');
insert into stadium (id, name) values (59, 'Estádio General Sylvio Raulino de Oliveira');
insert into stadium (id, name) values (60, 'Estádio General Sílvio Raulino de Oliveira');
insert into stadium (id, name) values (61, 'Estádio Germano Kruger');
insert into stadium (id, name) values (62, 'Estádio Giulite Coutinho');
insert into stadium (id, name) values (63, 'Estádio Governador Alberto Tavares Silva');
insert into stadium (id, name) values (64, 'Estádio Governador João Castelo - Castelão');
insert into stadium (id, name) values (65, 'Estádio Governador Magalhães Pinto');
insert into stadium (id, name) values (66, 'Estádio Governador Plácido Castelo');
insert into stadium (id, name) values (67, 'Estádio Governador Roberto Santos');
insert into stadium (id, name) values (68, 'Estádio Heriberto Hülse');
insert into stadium (id, name) values (69, 'Estádio Iliê Vidal');
insert into stadium (id, name) values (70, 'Estádio Ismael Benigno');
insert into stadium (id, name) values (71, 'Estádio Jacques da Luz');
insert into stadium (id, name) values (72, 'Estádio Joaquim Henrique Nogueira');
insert into stadium (id, name) values (73, 'Estádio Joaquim Portugal');
insert into stadium (id, name) values (74, 'Estádio Jonas Ferreira Duarte');
insert into stadium (id, name) values (75, 'Estádio Jorge Ismael de Biasi');
insert into stadium (id, name) values (76, 'Estádio Jornalista Mário Filho');
insert into stadium (id, name) values (77, 'Estádio José Gomes da Costa');
insert into stadium (id, name) values (78, 'Estádio José Mammoud Abbas');
insert into stadium (id, name) values (79, 'Estádio José Olimpio da Rocha');
insert into stadium (id, name) values (80, 'Estádio José Roriz Aguiar');
insert into stadium (id, name) values (81, 'Estádio José do Rego Maciel');
insert into stadium (id, name) values (82, 'Estádio João Cláudio de Vasconcelos Machado');
insert into stadium (id, name) values (83, 'Estádio Jânio Moraes');
insert into stadium (id, name) values (84, 'Estádio Leandro Cláudio da Silva');
insert into stadium (id, name) values (85, 'Estádio Leônidas Sodré de Castro');
insert into stadium (id, name) values (86, 'Estádio Lindolfo Monteiro');
insert into stadium (id, name) values (87, 'Estádio Luso Brasileiro');
insert into stadium (id, name) values (88, 'Estádio Lírio Callou');
insert into stadium (id, name) values (89, 'Estádio Major Antônio Couto Pereira');
insert into stadium (id, name) values (90, 'Estádio Manoel Barradas');
insert into stadium (id, name) values (91, 'Estádio Manoel Dantas Barreto');
insert into stadium (id, name) values (92, 'Estádio Maria Lamas Farache');
insert into stadium (id, name) values (93, 'Estádio Maria de Lourdes Abadia');
insert into stadium (id, name) values (94, 'Estádio Mauro Sampaio');
insert into stadium (id, name) values (95, 'Estádio Maximino Porpino Filho');
insert into stadium (id, name) values (96, 'Estádio Milton de Souza Corrêa');
insert into stadium (id, name) values (97, 'Estádio Moisés Lucarelli');
insert into stadium (id, name) values (98, 'Estádio Municipal 14 de Dezembro');
insert into stadium (id, name) values (99, 'Estádio Municipal Aluízio Pinheiro Ferreira');
insert into stadium (id, name) values (100, 'Estádio Municipal Anacleto Campanella');
insert into stadium (id, name) values (101, 'Estádio Municipal Antônio Dias');
insert into stadium (id, name) values (102, 'Estádio Municipal Antônio de Figueiredo Carneiro');
insert into stadium (id, name) values (103, 'Estádio Municipal Bento de Abreu Sampaio Vidal');
insert into stadium (id, name) values (104, 'Estádio Municipal Coaracy da Mata Fonseca');
insert into stadium (id, name) values (105, 'Estádio Municipal Doutor Novelli Júnior');
insert into stadium (id, name) values (106, 'Estádio Municipal Dr. Rafael Seabra');
insert into stadium (id, name) values (107, 'Estádio Municipal Eduardo José Farah');
insert into stadium (id, name) values (108, 'Estádio Municipal Engenheiro Luthero Lopes');
insert into stadium (id, name) values (109, 'Estádio Municipal Felipe Raulino');
insert into stadium (id, name) values (110, 'Estádio Municipal Gentil Valério');
insert into stadium (id, name) values (111, 'Estádio Municipal Gerson do Amaral');
insert into stadium (id, name) values (112, 'Estádio Municipal Governador Antônio Mariz');
insert into stadium (id, name) values (113, 'Estádio Municipal Helvídio Nunes de Barros');
insert into stadium (id, name) values (114, 'Estádio Municipal Irmão Gino Maria Rossi');
insert into stadium (id, name) values (115, 'Estádio Municipal Jacy Scaff');
insert into stadium (id, name) values (116, 'Estádio Municipal Jairton Menezes de Mendonça');
insert into stadium (id, name) values (117, 'Estádio Municipal José María de Campos Maia');
insert into stadium (id, name) values (118, 'Estádio Municipal João Lamego Netto');
insert into stadium (id, name) values (119, 'Estádio Municipal Marcos Pinheiro Neto');
insert into stadium (id, name) values (120, 'Estádio Municipal Nhozinho Santos');
insert into stadium (id, name) values (121, 'Estádio Municipal Parque do Sabiá');
insert into stadium (id, name) values (122, 'Estádio Municipal Paulo Machado de Carvalho');
insert into stadium (id, name) values (123, 'Estádio Municipal Pedro Alelaf');
insert into stadium (id, name) values (124, 'Estádio Municipal Plácido Aderaldo Castelo');
insert into stadium (id, name) values (125, 'Estádio Municipal Prefeito Dilzon Luiz de Melo');
insert into stadium (id, name) values (126, 'Estádio Municipal Radialista Mário Helênio');
insert into stadium (id, name) values (127, 'Estádio Municipal Raimundo de Oliveira');
insert into stadium (id, name) values (128, 'Estádio Municipal Roberto Santos Garcia');
insert into stadium (id, name) values (129, 'Estádio Municipal Valdir Doilho Wons');
insert into stadium (id, name) values (130, 'Estádio Municipal Vereador Benedito Laurindo de Souza ou Estádio Dito');
insert into stadium (id, name) values (131, 'Estádio Municipal Zinho de Oliveira');
insert into stadium (id, name) values (132, 'Estádio Mário Pinto de Souza');
insert into stadium (id, name) values (133, 'Estádio Nabi Abi Chedid');
insert into stadium (id, name) values (134, 'Estádio Nacional de Brasília Mané Garrincha');
insert into stadium (id, name) values (135, 'Estádio Nilton Santos');
insert into stadium (id, name) values (136, 'Estádio Olimpico Albino Turbay');
insert into stadium (id, name) values (137, 'Estádio Olímpico Colosso da Lagoa');
insert into stadium (id, name) values (138, 'Estádio Olímpico Monumental');
insert into stadium (id, name) values (139, 'Estádio Olímpico Municipal Gilberto Mestrinho');
insert into stadium (id, name) values (140, 'Estádio Olímpico Nilton Santos');
insert into stadium (id, name) values (141, 'Estádio Olímpico Pedro Ludovico Teixeira');
insert into stadium (id, name) values (142, 'Estádio Olímpico Regional Arnaldo Busatto');
insert into stadium (id, name) values (143, 'Estádio Olímpio Perim');
insert into stadium (id, name) values (144, 'Estádio Onésio Brasileiro Alvarenga');
insert into stadium (id, name) values (145, 'Estádio Orlando Scarpelli');
insert into stadium (id, name) values (146, 'Estádio Paulo Barreto de Menezes');
insert into stadium (id, name) values (147, 'Estádio Paulo Constantino');
insert into stadium (id, name) values (148, 'Estádio Presidente Vargas');
insert into stadium (id, name) values (149, 'Estádio Primeiro de Maio');
insert into stadium (id, name) values (150, 'Estádio Proletário Guilherme da Silveira');
insert into stadium (id, name) values (151, 'Estádio Raimundo Sampaio');
insert into stadium (id, name) values (152, 'Estádio Regional Willie Davids');
insert into stadium (id, name) values (153, 'Estádio Rei Pelé');
insert into stadium (id, name) values (154, 'Estádio Renato Cunha Lima');
insert into stadium (id, name) values (155, 'Estádio Salvador Venâncio da Costa');
insert into stadium (id, name) values (156, 'Estádio Santa Cruz');
insert into stadium (id, name) values (157, 'Estádio Senador João Ribeiro');
insert into stadium (id, name) values (158, 'Estádio Serra Dourada');
insert into stadium (id, name) values (159, 'Estádio Soares de Azevedo');
insert into stadium (id, name) values (160, 'Estádio São Benedito');
insert into stadium (id, name) values (161, 'Estádio São Januário');
insert into stadium (id, name) values (162, 'Estádio Universitário Pedro Pedrossian');
insert into stadium (id, name) values (163, 'Estádio Urbano Caldeira');
insert into stadium (id, name) values (164, 'Estádio Vail Chaves');
insert into stadium (id, name) values (165, 'Estádio Valdeir José de Oliveira');
insert into stadium (id, name) values (166, 'Estádio Valmir Campelo Bezerra');
insert into stadium (id, name) values (167, 'Estádio Vianão');
insert into stadium (id, name) values (168, 'Estádio Zama Maciel');
insert into stadium (id, name) values (169, 'Estádio Zenor Pedrosa Rocha');
insert into stadium (id, name) values (170, 'Estádio de Hailé Pinheiro');
insert into stadium (id, name) values (171, 'Estádio de Los Larios');
insert into stadium (id, name) values (172, 'Estádio do Governo do Estado de Goiás');
insert into stadium (id, name) values (173, 'Estádio do Trabalhador');
insert into stadium (id, name) values (174, 'Estádio do Vale');
insert into stadium (id, name) values (175, 'Estádio dos Plátanos');
insert into stadium (id, name) values (176, 'Estádio Érton Coelho de Queiroz');
insert into stadium (id, name) values (177, 'Itaipava Arena Pernambuco');
insert into stadium (id, name) values (178, 'Laerte Pais Coelho');
insert into stadium (id, name) values (179, 'Ligga Arena');
insert into stadium (id, name) values (180, 'Morenão');
insert into stadium (id, name) values (181, 'Neo Química Arena');
insert into stadium (id, name) values (182, 'Neo Química Arena');
insert into stadium (id, name) values (183, 'Os Pioneiros');
insert into stadium (id, name) values (184, 'Pinheirão');


 